### PR TITLE
Ensure queue data for `members`, etc is sorted upon input

### LINKED ISSUE #10929: HTTP API: GET /api/queues/{vhost}/{name} can return duplicate keys for quorum queues
### Describe the bug

API requests like the following will return duplicated `online` and `members` keys in the JSON:

```
curl -4su guest:guest localhost:15672/api/queues/%2F/perf-test-000
```

### Reproduction steps

* Start a `3.13.x` cluster
    ```
    make PLUGINS='rabbitmq_management rabbitmq_top' NODES=3 start-cluster
    ```
* Start PerfTest
    From source:
    ```
    make ARGS='--uris amqp://localhost:5672,amqp://localhost:5673,amqp://localhost:5674 --rate=100 --producers=10 --consumers=10 --quorum-queue --queue-pattern=perf-test-%03d --queue-pattern-from=0 --queue-pattern-to=9' run
    ```
* Make REST request
    ```
    curl -4su guest:guest localhost:15672/api/queues/%2F/perf-test-000
    ```
* Note that the output has duplicated `members` and `online` keys. Do _NOT_ run the output through any pretty-printers because they will most likely remove duplicated data!
    ```
    curl -4su 'guest:guest' 'localhost:15672/api/queues/%2F/perf-test-000'
    {"consumer_details":[{"arguments":{},"channel_details":{"connection_name":"127.0.0.1:47740 -> 127.0.0.1:5673","name":"127.0.0.1:47740 -> 127.0.0.1:5673 (1)","node":"rabbit-2@shostakovich","number":1,"peer_host":"127.0.0.1","peer_port":47740,"user":"guest"},"ack_required":true,"active":true,"activity_status":"up","consumer_tag":"amq.ctag-7QnoMZQOa2E7WEO3JJRb7w","consumer_timeout":1800000,"exclusive":false,"prefetch_count":0,"queue":{"name":"perf-test-000","vhost":"/"}}],"arguments":{"x-queue-type":"quorum"},"auto_delete":false,"consumer_capacity":1.0,"consumer_utilisation":1.0,"consumers":1,"deliveries":[],"durable":true,"effective_policy_definition":{},"exclusive":false,"garbage_collection":{"fullsweep_after":65535,"max_heap_size":0,"min_bin_vheap_size":46422,"min_heap_size":233,"minor_gcs":63},"incoming":[],"leader":"rabbit-1@shostakovich","members":["rabbit-1@shostakovich","rabbit-2@shostakovich","rabbit-3@shostakovich"],"members":["rabbit-1@shostakovich","rabbit-3@shostakovich","rabbit-2@shostakovich"],"memory":90580,"message_bytes":24,"message_bytes_dlx":0,"message_bytes_persistent":24,"message_bytes_ram":0,"message_bytes_ready":0,"message_bytes_unacknowledged":24,"message_stats":{"ack":391,"ack_details":{"rate":0.0},"deliver":391,"deliver_details":{"rate":0.0},"deliver_get":391,"deliver_get_details":{"rate":0.0},"deliver_no_ack":0,"deliver_no_ack_details":{"rate":0.0},"get":0,"get_details":{"rate":0.0},"get_empty":0,"get_empty_details":{"rate":0.0},"get_no_ack":0,"get_no_ack_details":{"rate":0.0},"publish":392,"publish_details":{"rate":0.0},"redeliver":0,"redeliver_details":{"rate":0.0}},"messages":2,"messages_details":{"rate":0.0},"messages_dlx":0,"messages_persistent":2,"messages_ram":0,"messages_ready":0,"messages_ready_details":{"rate":0.0},"messages_unacknowledged":2,"messages_unacknowledged_details":{"rate":0.0},"name":"perf-test-000","node":"rabbit-1@shostakovich","online":["rabbit-1@shostakovich","rabbit-2@shostakovich","rabbit-3@shostakovich"],"online":["rabbit-1@shostakovich","rabbit-3@shostakovich","rabbit-2@shostakovich"],"open_files":{"rabbit-1@shostakovich":0,"rabbit-2@shostakovich":0,"rabbit-3@shostakovich":0},"operator_policy":null,"policy":null,"reductions":1088173,"reductions_details":{"rate":0.0},"single_active_consumer_tag":"amq.ctag-7QnoMZQOa2E7WEO3JJRb7w","state":"running","type":"quorum","vhost":"/"}
    ```

### Expected behavior

No duplicates.

### Additional context

This was first reported in VESC-1102.

This is due to the order of `online` and `members` proplist value changing between 3.12.x and 3.13.x. In `rabbit_mgmt_format:strip_pids`, `lists:usort` is used to remove duplicates, but since the values do not compare as equal in 3.13.x, the duplicates are not removed:

* `3.13.x` input example
```
1> lists:usort([{members, ['rabbit@rmq0.local','rabbit@rmq1.local', 'rabbit@rmq2.local']}, {members, ['rabbit@rmq1.local','rabbit@rmq2.local', 'rabbit@rmq0.local']}]).
[{members,['rabbit@rmq0.local','rabbit@rmq1.local',
           'rabbit@rmq2.local']},
 {members,['rabbit@rmq1.local','rabbit@rmq2.local',
           'rabbit@rmq0.local']}]
```

* `3.12.x` input example:
```
2> lists:usort([{members, ['rabbit@rmq0.local','rabbit@rmq1.local', 'rabbit@rmq2.local']}, {members, ['rabbit@rmq0.local','rabbit@rmq1.local', 'rabbit@rmq2.local']}]).
[{members,['rabbit@rmq0.local','rabbit@rmq1.local', 'rabbit@rmq2.local']}]
```

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #10929

### CODE REVIEW

File: deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl [hunk 1]
```diff
@@ -78,6 +78,12 @@ format_queue_stats({disk_reads, _}) ->
     [];
 format_queue_stats({disk_writes, _}) ->
     [];
+format_queue_stats({members, Value}) ->
+    [{members, lists:sort(Value)}];
```
Comment (michaelklishin) [inline deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl:82]: Should this be `lists:usort/1`? `lists:sort/1` does not eliminate duplicates but `lists:usort/1` does.

Comment (michaelklishin) [reply deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl:82]: Perhaps I misunderstood the intent. If sorting members addresses the root cause. This can be enough. In theory, there should be no duplicate members reported by a QQ.

**Review by michaelklishin — APPROVED** [review]
