### PR TITLE
Return policy fields and `delivery_limit` when stats are disabled

### LINKED ISSUE #15182: Disabling management statistics removes non-stats data from HTTP API
### Describe the bug

Related discussion: https://github.com/rabbitmq/rabbitmq-server/discussions/15146

Repository with RabbitMQ configuration and reproduction details: https://github.com/lukebakken/rabbitmq-server-15146

TL;DR these two settings in `rabbitmq.conf`...

```
management_agent.disable_metrics_collector = true
management.disable_stats = true
```

...cause non-stats-related data to no longer be present via HTTP API requests.

### Reproduction steps

Please see https://github.com/lukebakken/rabbitmq-server-15146/tree/main?tab=readme-ov-file#repro-steps

### Expected behavior

Data like policy names is preserved in HTTP API even when stats are disabled.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lukebakken**
When `management_agent.disable_metrics_collector` and `management.disable_stats` are both set to `true`, the HTTP API returns minimal queue information that excludes policy-related fields and `delivery_limit`. This causes `policy`, `operator_policy`, `effective_policy_definition`, and `delivery_limit` to be `null` in API responses, even though these are configuration metadata rather than statistics.

This change adds these four fields to the `format/2` function in both `rabbit_classic_queue` and `rabbit_quorum_queue` modules. The fields now appear in the type-specific formatting that runs regardless of metrics collection status. The three policy fields use existing `i/2` function implementations that call `rabbit_policy` module functions. For `delivery_limit`, this change adds an `i(delivery_limit, Q)` function to `rabbit_quorum_queue` that extracts the delivery limit from the queue's `x-delivery-limit` argument, returning `unlimited` when not set.

Fixes #15182

### CODE REVIEW

File: deps/rabbit/src/rabbit_quorum_queue.erl [hunk 1]
```diff
@@ -1887,6 +1887,12 @@ i(message_bytes_dlx, Q) when ?is_amqqueue(Q) ->
         {timeout, _} ->
             0
     end;
+i(delivery_limit, Q) when ?is_amqqueue(Q) ->
+    Args = amqqueue:get_arguments(Q),
+    case rabbit_misc:table_lookup(Args, <<"x-delivery-limit">>) of
+        undefined -> unlimited;
```
Comment (gomoripeti) [inline deps/rabbit/src/rabbit_quorum_queue.erl]: I'm not sure if this is intentional, but this is not the same as what is returned today, if a policy applies a delivery limit. One correct value would be to do a local_query to get delivery_limit from the fifo state. A cheaper way is to merge the values from queue args and effective policy the same way as calculated when the policy is applied. (https://github.com/amazon-mq/upstream-to-rabbitmq-server/blob/90c37006c0d0d727aaaeb62a2b8afd29a1cb9509/deps/rabbit/src/rabbit_quorum_queue.erl#L346)
(I've seen a case where the value in the fifo state was different than what it should be based on calculation (and the mgmt UI showing the wrong value from fifo state revealed this), but assuming a bug-free behaviour this should not happen.)

Comment (lukebakken) [reply deps/rabbit/src/rabbit_quorum_queue.erl]: Funny, I just realized that this code didn't pick up the default if `x-delivery-limit` isn't there, refreshed my page, and saw your comment 😸

**Comment by lukebakken** [comment]
@michaelklishin anything else to do here or are you waiting until closer to the 4.3 release to merge? Just curious, thanks.

**Comment by michaelklishin** [comment]
@lukebakken I'll review this PR today. Thank you.

**Comment by lukebakken** [comment]
Thanks!
