### PR TITLE
Ensure resources are cleaned up when connection socket is closed before Ranch handshake completes

### LINKED ISSUE #1901: `rabbit_networking:handshake/2` doesn't handle the scenario where the socket is closed before Proxy protocol header can be retrieved
From [this rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/O0X5cIddJC4):

`rabbit_networking:handshake/2` doesn't handle the scenario where the socket is closed before Proxy protocol header can be retrieved and parsed. The resulting exception is harmless in practice but produces scary looking log entries.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #1901

I'm not 100% sure this is the right way to clean up when `ranch:recv_proxy_header` but I think this makes sense.

Also see: https://groups.google.com/d/topic/rabbitmq-users/3HAMNDucUPI/discussion

### CODE REVIEW

File: src/rabbit_networking.erl [hunk 1]
```diff
@@ -389,13 +389,29 @@ force_connection_event_refresh(Ref) ->
...
-    case ProxyProtocol of
+failed_to_recv_proxy_header(Ref, Error) ->
+    Msg = case Error of
+        closed -> "error when receiving proxy header: TCP socket was ~p prematurely";
+        _Other -> "error when receiving proxy header: ~p"
+    end,
+    rabbit_log:error(Msg, [Error]),
+    % The following call will clean up resources then exit
+    _ = ranch:handshake(Ref),
+    exit({shutdown, failed_to_recv_proxy_header}).
```
Comment (lukebakken) [inline src/rabbit_networking.erl]: @michaelklishin I don't think that this line will be reached in a real `{error, closed}` situation as `ranch:handshake` should exit [here](https://github.com/ninenines/ranch/blob/master/src/ranch.erl#L251-L253). But, there's no harm in leaving this `exit` call in.

**Comment by lukebakken** [comment]
Backported to `v3.7.x`
