### PR TITLE
Limit number of unique node names for rabbitmqctl

### LINKED ISSUE #549: Atom table exhaustion due to rabbitmqctl node names
rabbitmqctl generate node names like 'rabbit-cli-&lt;pid&gt;@&lt;host&gt;'. The problem is that node names are stored in atom table and not garbage collected. 

Some numbers:
- Maximum pid number on linux is 32768 by default
- Maximum pid  could be increased to ~4 millions on 64-bit CPU
- Erlang atom table has default limit of 1048576 atoms.

So on linux any long running rabbitmqbroker could be crashed by constantly running rabbitmqctl:
- in cluster of more than 32 nodes (with default pid limit)
- or even on single node, after increasing that limit

While it sounds ridiculous, we've observed such a crash on a production server  )

There should be some way to generate rabbitmqctl nodenames without introducing large quantities of uncollected garbage.

### PR DESCRIPTION
**Pull request by binarin**
It prevents atom table overflow in a long running broker.

Fixes #549

### CODE REVIEW

File: src/rabbit_cli.erl [hunk 1]
```diff
@@ -125,9 +135,22 @@ main(ParseFun, DoFun, UsageMod) ->
             rabbit_misc:quit(?EX_SOFTWARE)
     end.
 
+start_distribution_anon(0, LastError) ->
+    {error, LastError};
+start_distribution_anon(TriesLeft, _) ->
+    NameCandidate = list_to_atom(rabbit_misc:format("rabbitmq-cli-~2..0b", [rabbit_misc:random(100)])),
```
Comment (hairyhum) [inline src/rabbit_cli.erl]: `rabbit_misc:random` is undefined.

Comment (binarin) [inline src/rabbit_cli.erl]: Yeah, you'll need https://github.com/rabbitmq/rabbitmq-common/pull/48
And also you can't simply run ./scripts/rabbitmqctl from rabbitmq-server checkout - rabbit_common will be missing from code path (but on installed server it will be available through rabbit_common.ez archive).

Comment (michaelklishin) [inline src/rabbit_cli.erl]: One can run `make package-generic-unix UNOFFICIAL_RELEASE=true` from the umbrella to produce a tarball. It should take a couple of minutes.

Comment (binarin) [inline src/rabbit_cli.erl]: Then every sequence of "random" numbers will be the same - and it's exactly the thing that we want to avoid, to reduce contention.
