### PR TITLE
Make it possible to delete or restart a dynamic Shovel on/from any cluster node (take two)

### LINKED ISSUE #2807: Allow shovel deletion from any node
Reproduction steps: 
- Start a 3-node cluster
- Create a shovel on any node
- Delete the shovel from a node that it's not running on 
- Experience an error message, unless you do this with the http API then the shovel is deleted but still present on the "Shovel Status" page

The error message seems to be an result of this issue: https://github.com/rabbitmq/rabbitmq-shovel/issues/68 except that it does not work when using the http API

Resolution: RabbitMQ should delete the shovel on the correct node regardless of which node that receives the delete request

### PR DESCRIPTION
**Pull request by michaelklishin**
## Proposed Changes

This builds on #4127 by @kostakal. Closes #2807.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [x] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

File: deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt.erl [hunk 1]
```diff
@@ -107,52 +114,30 @@ filter_vhost_req(List, ReqData) ->
...
-
-print(Fmt, Val) ->
-    list_to_binary(io_lib:format(Fmt, Val)).
+%% This is similar to rabbit_shovel_status:find_matching_shovel/3
+%% but operates on a different input (a proplist of Shovel attributes)
+-spec find_matching_shovel(VHost :: vhost:name(),
+                           Name :: binary(),
+                           Shovels :: list()) -> 'undefined' | node().
+find_matching_shovel(VHost, Name, Shovels) ->
+    Matches = lists:filter(
```
Comment (pjk25) [inline deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt.erl:133]: maybe `lists:search/2` would be more appropriate (and possibly address the dialyzer warning)
