### PR TITLE
rabbit_definitions: ensure federation-upstream-set parameters are exported

### LINKED ISSUE #11612: Failure to export some runtime parameters in rabbitmqctl export_definitions
### Describe the bug

`export_definitions` of `federation-upstream-set` parameters fails during export because of formatting errors:

```
rabbitmqctl export_definitions def.json
Exporting definitions in JSON to a file at "def.json" ...
Error:
{:badarg, [{:maps, :from_list, [[%{"upstream" => "up-1"}, %{"upstream" => "up-2"}]], [error_info: %{module: :erl_stdlib_errors}]}, {:rabbit_definitions, :runtime_parameter_definition, 1, [file: ~c"rabbit_definitions.erl", line: 1084]}, {:rabbit_definitions, :"-list_runtime_parameters/0-lc$^0/1-0-", 1, [file: ~c"rabbit_definitions.erl", line: 1077]}, {:rabbit_definitions, :all_definitions, 0, [file: ~c"rabbit_definitions.erl", line: 275]}]}
```

This was reported for 3.12.4 but can be reproduced in main

### Reproduction steps

1. Start a node with `rabbitmq_federation` enabled
2. Set `rabbitmqctl set_parameter federation-upstream-set location-1 '[{"upstream": "up-1"}, {"upstream": "up-2"}]'`
3. Export `rabbitmqctl export_definitions def.json`

### Expected behavior

Definitions should be exported successfully

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dcorbacho**
These parameters are not proplists but a list of maps

Closes #11612 

## Types of Changes

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

File: deps/rabbit/src/rabbit_definitions.erl [hunk 1]
```diff
@@ -1081,9 +1081,22 @@ runtime_parameter_definition(Param) ->
         <<"vhost">> => pget(vhost, Param),
         <<"component">> => pget(component, Param),
         <<"name">> => pget(name, Param),
-        <<"value">> => maps:from_list(pget(value, Param))
+        <<"value">> => maybe_map(pget(value, Param))
```
Comment (michaelklishin) [inline deps/rabbit/src/rabbit_definitions.erl:1084]: should we simply use `rabbit_data_coercion:to_map/1` here?

**Comment by michaelklishin** [comment]
CI fails because the new suite needs a few more Bazel rules.

**Review by michaelklishin — APPROVED** [review]
