### PR TITLE
Start mirrors synchronously when transferring CMQ leadership

### LINKED ISSUE #2749: Classic mirrored queue leadership transfer eagerly clears the list of mirrors which can result in data loss
## Describe the bug

Data loss issue with mirror queues on operator deployed clusters. Reported by internal team. cc @mkuratczyk @Gsantomaggio 

## To Reproduce
1. Deploy 3 nodes rabbitmq cluster
2. Create HA policy with params: "ha-mode: exactly, ha-params: 2, ha-promote-on-failure: when-synced, ha-sync-batch-size: 5000, ha-sync-mode: automatic"
3. Use perf tests to populate the cluster with unconsumed messages `-y0 -queue-pattern 'perf-test-%d' \
--auto-delete false --queue-pattern-from 1 --queue-pattern-to 10  -s 1000 -x 10 -y 0 -r 1000 -R 0  -f persistent`
4. Stop perf-tests (without triggering any alarms and all queues should be synced)
5. Delete one node which has queue masters located on and observe data loss (0 message left)

Include any YAML or manifest necessary to reproduce the problem.

**Expected behavior**

After deleting one rabbitmq node, the mirror queue should be promoted as the master queue and rabbitmq should create a new mirror in node that's not deleted.

## Screenshots

data loss

## Version and environment information
- RabbitMQ: 3.8.9
- RabbitMQ Cluster Operator: Latest main: https://github.com/rabbitmq/cluster-operator/commit/c4206617eaac1a895936e9f805ae7586cc3c49f0
- Kubernetes: 1.17.0
- Cloud provider or hardware configuration:
 
## Additional context

This is a reported issue. The user has also seem similar data loss with "ha-params: 3" on 5 nodes cluster.

### PR DESCRIPTION
**Pull request by michaelklishin**
## Proposed Changes

This changes classic mirror queue leadership transfer to add mirrors synchronously and also delete
fewer mirrors where it's not warranted.

We also used this as an opportunity to rename a few things around the relevant code paths.

Closes #2749.
References #2737.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes issue #2749)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in related repositories

## Further Comments

Pairs: @dcorbacho @mkuratczyk.

### CODE REVIEW

**Comment by michaelklishin** [comment]
We are considering exclude CMQ leadership transfer from maintenance mode because it can take quite some time in clusters with a lot of queue, and this cannot really be optimized. Quorum queues transfer leadership a lot more efficiently, so that can stay. However, this change can be merged as is.

File: deps/rabbit/src/rabbit_mirror_queue_misc.erl [hunk 1]
```diff
@@ -201,12 +201,13 @@ drop_mirror(QName, MirrorNode) ->
     case rabbit_amqqueue:lookup(QName) of
         {ok, Q} when ?is_amqqueue(Q) ->
             Name = amqqueue:get_name(Q),
-            QPid = amqqueue:get_pid(Q),
-            SPids = amqqueue:get_slave_pids(Q),
-            case [Pid || Pid <- [QPid | SPids], node(Pid) =:= MirrorNode] of
+            PrimaryPid = amqqueue:get_pid(Q),
```
Comment (NickGrantONS) [inline deps/rabbit/src/rabbit_mirror_queue_misc.erl:204]: John O'Hara - inventor of AMQP - will be sad to see the demise of QPid - AMQP's first implementation - from the RabbitMQ codebase

Comment (michaelklishin) [reply deps/rabbit/src/rabbit_mirror_queue_misc.erl:204]: Hahaha. Definitely a good one 🤓
