### PR TITLE
Log a more sensible error message when running on an outdated Erlang version

### LINKED ISSUE #1307: Log a sensible message when Erlang/OTP version is too old
Discovered with @dumbbell as part of #1305. We currently log something that kind of has a hint but most users won't find it useful:

```
2017-07-26 17:59:46.774 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: {{erlang_version_too_old,{found,"18.3.3","7.3.1"},{required,"19.2","8.2"}},{rabbit,start,[normal,[]]}} in application_master:init/4 line 134
2017-07-26 17:59:46.774 [info] <0.7.0> Application rabbit exited with reason: {{erlang_version_too_old,{found,"18.3.3","7.3.1"},{required,"19.2","8.2"}},{rabbit,start,[normal,[]]}}
```

### PR DESCRIPTION
**Pull request by michaelklishin**
Closes #1307.
[#149635897#]

### CODE REVIEW

File: src/rabbit.erl [hunk 1]
```diff
@@ -803,6 +803,16 @@ start(normal, []) ->
...
             rabbit_boot_steps:run_boot_steps(),
             {ok, SupPid};
+        {error, {erlang_version_too_old,
+                 {found, OTPRel, ERTSVer},
+                 {required, ?OTP_MINIMUM, ?ERTS_MINIMUM}}} ->
+            Msg = "This RabbitMQ version cannot run on Erlang ~s (erts ~s): "
+                  "minimum required version is ~s (erts ~s)",
+            Args = [OTPRel, ERTSVer, ?OTP_MINIMUM, ?ERTS_MINIMUM],
+            rabbit_log:error(Msg, Args),
+            %% also print to stdout to make this more visible
```
Comment (lukebakken) [inline src/rabbit.erl]: `stderr` instead maybe?
