### PR TITLE
rabbit_peer_discovery: Pass inetrc config file to temporary hidden node

### LINKED ISSUE #10728: RabbitMQ 3.13.0 nodes with peer discovery enabled fails to start in an IPv6-only environment
### Describe the bug

In OpenStack Kolla-Ansible we support ipv6-only OpenStack deployments, including RabbitMQ.
The following config worked up until RMQ 3.13:

https://8dff850f95026878e224-be64ab2c1211c8399b7ac2efe4751a63.ssl.cf2.rackcdn.com/911094/2/check/kolla-ansible-rocky9-multinode-ipv6/4952d5c/primary/logs/kolla_configs/rabbitmq/rabbitmq.conf

https://8dff850f95026878e224-be64ab2c1211c8399b7ac2efe4751a63.ssl.cf2.rackcdn.com/911094/2/check/kolla-ansible-rocky9-multinode-ipv6/4952d5c/primary/logs/kolla_configs/rabbitmq/index.html

Logs and crash dump here: https://8dff850f95026878e224-be64ab2c1211c8399b7ac2efe4751a63.ssl.cf2.rackcdn.com/911094/2/check/kolla-ansible-rocky9-multinode-ipv6/4952d5c/primary/logs/kolla/rabbitmq/index.html

### Reproduction steps

1. Use config from description to start RMQ 3.13
2.
3.
...

### Expected behavior

Runs correctly

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dumbbell**
## Why

As shown in #10728, in an IPv6-only environment, `kernel` name resolution must be configured through an inetrc file.

The temporary hidden node must be configured exactly like the main node (and all nodes in the cluster in fact) to allow communication. Thus we must pass the same inetrc file to that temporary hidden node. This wasn’t the case before this patch.

## How

We query the main node’s kernel to see if there is any inetrc file set and we use the same on the temporary hidden node’s command line.

While here, extract the handling of the `proto_dist` module from the TLS code. This parameter may be used outside of TLS like this IPv6-only environment.

Fixes #10728.

### CODE REVIEW

**Comment by lukebakken** [comment]
You know, I haven't tested any of this "hidden node" stuff on Windows. I'll make time to do that with this patch and will test TLS-enabled distribution as well.

**Comment by dumbbell** [comment]
> You know, I haven't tested any of this "hidden node" stuff on Windows. I'll make time to do that with this patch and will test TLS-enabled distribution as well.

That would be great! Thank you very much :-)

**Comment by lukebakken** [comment]
I'm just making a note here that this PR is a follow-up to https://github.com/rabbitmq/rabbitmq-server/pull/10194

File: deps/rabbit/src/rabbit_peer_discovery.erl [hunk 1]
```diff
@@ -423,27 +425,45 @@ query_node_props(Nodes) when Nodes =/= [] ->
...
-            add_tls_arguments(inet6_tls, VMArgs0);
+        {ok, [[Val]]} ->
+            %% Note:
+            %%
+            %% We can't use list_to_existing_atom/1 because
+            %% the atom doesn't actually already exist.
+            %%
+            %% See net_kernel.erl / protocol_childspecs/1
+            Mod = list_to_atom(Val ++ "_dist"),
+            ModDir = filename:dirname(code:which(Mod)),
```
Comment (dumbbell) [inline deps/rabbit/src/rabbit_peer_discovery.erl:438]: @lukebakken: If the atom may not exist, is the module loaded then? I don't think we can compare the context of `net_kernel` to the Peer discovery subsystem. `net_kernel` is used very early and is responsible for loading the distribution module and setting the distribution up.

When peer discovery runs, the distribution module must be loaded already. Thus I'm surprised that the atom doesn't exist.

I mean, it's not a big deal, we can use `list_to_atom/1` instead of `list_to_existing_atom/1`, but the comment seems incorrect in the context of peer discovery (it can be true in `net_kernel`).

Where you able to reproduce an exception with `list_to_existing_atom/1`? I understand there was a mistake in the original code where the `_dist` suffix was not appended.

Comment (lukebakken) [reply deps/rabbit/src/rabbit_peer_discovery.erl:438]: > Where you able to reproduce an exception with list_to_existing_atom/1

Aha, I bet I got the exception because the `_dist` suffix had not been added. I will re-test with `list_to_existing_atom/1`

Comment (lukebakken) [reply deps/rabbit/src/rabbit_peer_discovery.erl]: Yep, that was it!

**Comment by lukebakken** [comment]
OK, I built a Windows zip with this PR, and the `inetrc` argument is passed to the peer node at startup:

```
Peer discovery: peer node arguments: #{args =>
                                           ["-ssl_dist_optfile",
                                            "C:/Users/lbakken/development/lukebakken/windows-rabbitmq-cluster/rmq1 Евгений/inter_node_tls.config",
                                            "-kernel","inetrc",
                                            "\"C:/Users/lbakken/development/lukebakken/windows-rabbitmq-cluster/erl_inetrc\"",
                                            "-proto_dist","inet_tls","-pa",
                                            "c:/Users/lbakken/scoop/apps/erlang/26.2.3/lib/ssl-11.1.2/ebin",
                                            "-boot","start_sasl","-hidden"],
                                       name => "rmq1-4-22800"}
```

Cluster formation worked correctly, as well. Here is the `erl_inetrc` file I used:

https://github.com/lukebakken/windows-rabbitmq-cluster/blob/tls-disterl-utf8/erl_inetrc

**Review by lukebakken — APPROVED** [review]

**Comment by michaelklishin** [comment]
The reporter suggests that a package built off of this branch does work as expected (the way 3.12.x did in the same environment) https://github.com/rabbitmq/rabbitmq-server/issues/10728#issuecomment-2018356640.

**Comment by michaelklishin** [comment]
The forced push was a rebase.

**Comment by dumbbell** [comment]
The patch was not ready (hence the draft status) and should not have been merged. I reverted it.
