### PR TITLE
Handle void types in AMQP 0.9.1 -> AMQP 1.0 conversion

### LINKED ISSUE #4831: Crash when publishing using AMQP 0.9.1 to a stream when a header item has a void value
The 0.9.1 to 1.0 message conversion fails when an 0.9.1 header value with a `void` type is encountered.

Sample content record:

```{content,60,
         {'P_basic',<<"application/json">>,<<"utf-8">>,
                    [{<<"lang">>,longstr,<<"py">>},
                     {<<"task">>,longstr,<<"api.tasks.test1">>},
                     {<<"id">>,longstr,
                      <<"79c107c1-8c2b-43a5-b7e7-db8ec72c5abf">>},
                     {<<"eta">>,void,undefined},
                     {<<"expires">>,void,undefined},
                     {<<"group">>,void,undefined},
                     {<<"retries">>,signedint,0},
                     {<<"timelimit">>,array,[{void,undefined},{void,undefined}]},
                     {<<"root_id">>,longstr,
                      <<"79c107c1-8c2b-43a5-b7e7-db8ec72c5abf">>},
                     {<<"parent_id">>,void,undefined},
                     {<<"argsrepr">>,longstr,<<"(3,)">>},
                     {<<"kwargsrepr">>,longstr,<<"{}">>},
                     {<<"origin">>,longstr,<<"gen7494@epfo-qa">>}],
                    2,undefined,<<"79c107c1-8c2b-43a5-b7e7-db8ec72c5abf">>,
                    <<"e68f15cd-1965-32de-b751-688fab2614f0">>,undefined,
                    undefined,undefined,undefined,undefined,undefined,undefined},
         <<246,0,16,97,112,112,108,105,99,97,116,105,111,110,47,
           106,115,111,110,5,117,116,102,45,56,...>>,
         rabbit_framing_amqp_0_9_1,
         [<<"[[3], {}, {\"callbacks\": null, \"errbacks\": null, \"chain\": null, \"chord\": null}]">>]}```

### PR DESCRIPTION
**Pull request by kjnilsson**
void -> null
Fixes #4831

### CODE REVIEW

File: deps/rabbit/src/rabbit_msg_record.erl [hunk 1]
```diff
@@ -10,7 +10,7 @@
          message_annotation/3
          ]).
 
--include_lib("rabbit_common/include/rabbit.hrl").
+% -include_lib("rabbit_common/include/rabbit.hrl").
```
Comment (michaelklishin) [inline deps/rabbit/src/rabbit_msg_record.erl:13]: Is this intentional? If so, can we remove the line entirely?
