### PR TITLE
Make "global hang workaround" support OTP >= 25.1

### LINKED ISSUE #6034: Rolling updates hang on K8s with rabbitmq:3.11.0
The RabbitMQ “global hang workaround” as described in https://github.com/rabbitmq/rabbitmq-server/blob/238995be88951ef7f9eb3c650be5277358630229/deps/rabbit/src/rabbit_node_monitor.erl#L271-L285
breaks from OTP 25.1 onwards because the messages being sent in https://github.com/rabbitmq/rabbitmq-server/blob/238995be88951ef7f9eb3c650be5277358630229/deps/rabbit/src/rabbit_node_monitor.erl#L334-L337 are not handled anymore in `global` due to the following commit: https://github.com/erlang/otp/commit/9274e89857d294f85702e0d5d42fb196e8e12d6a

This means rolling updates in RabbitMQ on Kubernetes with image `rabbitmq:3.11.0` containing Erlang 25.1.1 will get (sometimes) stuck.

The reasoning of using "global hang workaround" is further described in https://github.com/rabbitmq/rabbitmq-server/pull/5438.
In short, a combination of the following issues leads us to relying on that workaround:
1. the new feature flags controller v2 introduced in 3.11 calls `global:sync/0` early on boot
2. following Kubernetes bug: https://github.com/kubernetes/kubernetes/issues/92559
3. Erlang `global` bug (got fixed in Erlang by setting parameter `prevent_overlapping_partitions` to `true`)
4. RabbitMQ not being able to set `prevent_overlapping_partitions` to `true` as described in https://github.com/rabbitmq/rabbitmq-server/pull/5483

To reproduce, trigger a few times a rolling update on `kindest/node:v1.25.2` using a 5 node RabbitMQ cluster with image `rabbitmq:3.11.0-management`.

The logs show the following before the node gets stuck:
```
2022-10-06 07:13:05.032492+00:00 [debug] <0.232.0> Register `rabbit` process (<0.232.0>) for rabbit_node_monitor

  ##  ##      RabbitMQ 3.11.0
  ##  ##
  ##########  Copyright (c) 2007-2022 VMware, Inc. or its affiliates.
  ######  ##
  ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com

  Erlang:      25.1.1 [jit]
  TLS Library: OpenSSL - OpenSSL 1.1.1q  5 Jul 2022
  Release series support status: supported

  Doc guides:  https://rabbitmq.com/documentation.html
  Support:     https://rabbitmq.com/contact.html
  Tutorials:   https://rabbitmq.com/getstarted.html
  Monitoring:  https://rabbitmq.com/monitoring.html

  Logs: /var/log/rabbitmq/rabbit@r1-server-2.r1-nodes.default_upgrade.log
        <stdout>

  Config file(s): /etc/rabbitmq/conf.d/10-defaults.conf
                  /etc/rabbitmq/conf.d/10-operatorDefaults.conf
                  /etc/rabbitmq/conf.d/11-default_user.conf
                  /etc/rabbitmq/conf.d/90-userDefinedConfiguration.conf

  Starting broker...2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>  node           : rabbit@r1-server-2.r1-nodes.default
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>  home dir       : /var/lib/rabbitmq
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>  config file(s) : /etc/rabbitmq/conf.d/10-defaults.conf
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>                 : /etc/rabbitmq/conf.d/10-operatorDefaults.conf
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>                 : /etc/rabbitmq/conf.d/11-default_user.conf
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>                 : /etc/rabbitmq/conf.d/90-userDefinedConfiguration.conf
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>  cookie hash    : idxtUKhQEU9Dav23AqS/0g==
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>  log(s)         : /var/log/rabbitmq/rabbit@r1-server-2.r1-nodes.default_upgrade.log
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>                 : <stdout>
2022-10-06 07:13:05.033106+00:00 [info] <0.232.0>  database dir   : /var/lib/rabbitmq/mnesia/rabbit@r1-server-2.r1-nodes.default
2022-10-06 07:13:05.033162+00:00 [debug] <0.232.0>
2022-10-06 07:13:05.033173+00:00 [debug] <0.232.0> == Plugins (prelaunch phase) ==
2022-10-06 07:13:05.033184+00:00 [debug] <0.232.0> Setting plugins up
2022-10-06 07:13:05.047274+00:00 [debug] <0.232.0> Plugins discovery: ignoring getopt, not a RabbitMQ plugin
2022-10-06 07:13:05.047316+00:00 [debug] <0.232.0> Plugins discovery: ignoring quantile_estimator, not a RabbitMQ plugin
2022-10-06 07:13:05.062932+00:00 [debug] <0.232.0> Loading the following plugins: [rabbitmq_management_agent,cowlib,cowboy,
2022-10-06 07:13:05.062932+00:00 [debug] <0.232.0>                                 rabbitmq_web_dispatch,amqp_client,
2022-10-06 07:13:05.062932+00:00 [debug] <0.232.0>                                 rabbitmq_management,prometheus,
2022-10-06 07:13:05.062932+00:00 [debug] <0.232.0>                                 rabbitmq_peer_discovery_common,accept,
2022-10-06 07:13:05.062932+00:00 [debug] <0.232.0>                                 rabbitmq_peer_discovery_k8s,
2022-10-06 07:13:05.062932+00:00 [debug] <0.232.0>                                 rabbitmq_prometheus]
2022-10-06 07:13:05.068152+00:00 [debug] <0.232.0> Feature flags: REFRESHING after applications load...
2022-10-06 07:13:05.068197+00:00 [debug] <0.377.0> Feature flags: registering controller globally before proceeding with task: refresh_after_app_load
2022-10-06 07:13:05.068231+00:00 [debug] <0.377.0> Feature flags: [global sync] @ rabbit@r1-server-2.r1-nodes.default
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0> Global hang workaround: global state on rabbit@r1-server-3.r1-nodes.default seems inconsistent
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>  * Peer global state:  {status,<25933.55.0>,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                         {module,gen_server},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                         [[{'$ancestors',[kernel_sup,<25933.47.0>]},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {rand_seed,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            {#{bits => 58,jump => #Fun<rand.3.34006561>,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               next => #Fun<rand.0.34006561>,type => exsss,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               uniform => #Fun<rand.1.34006561>,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               uniform_n => #Fun<rand.2.34006561>},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             [122137426785371025|262422651984364825]}},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {creation_extension,269151976804057088},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {'$initial_call',{global,init,1}}],
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                          running,<25933.49.0>,[],
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                          [{header,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            "Status for generic server global_name_server"},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {data,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            [{"Status",running},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             {"Parent",<25933.49.0>},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             {"Logged events",[]}]},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {data,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            [{"State",
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                              {state,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               {conf,true,false},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               #{'rabbit@r1-server-0.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-1.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-4.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  'rabbit@r1-server-0.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  12910273,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  'rabbit@r1-server-1.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  12823848,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  'rabbit@r1-server-2.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  13047845,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  'rabbit@r1-server-4.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  12992514},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               ['rabbit@r1-server-2.r1-nodes.default',
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                'rabbit@r1-server-4.r1-nodes.default',
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                'rabbit@r1-server-0.r1-nodes.default',
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                'rabbit@r1-server-1.r1-nodes.default'],
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               [],[],'rabbit@r1-server-3.r1-nodes.default',
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               <25933.56.0>,<25933.57.0>,no_trace,false}}]}]]}
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>  * Local global state: {status,<0.55.0>,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                         {module,gen_server},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                         [[{{pre_connect,'rabbit@r1-server-3.r1-nodes.default'},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            {8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             {locker,no_longer_a_pid,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                              #{'rabbit@r1-server-0.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                'rabbit@r1-server-1.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                'rabbit@r1-server-4.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-0.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 12910273,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-1.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 12823848,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-2.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 13047845,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-4.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 12992514},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                              <25933.56.0>},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             -576460752303423477}},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {{prot_vsn,'rabbit@r1-server-3.r1-nodes.default'},8},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {rand_seed,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            {#{bits => 58,jump => #Fun<rand.3.34006561>,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               next => #Fun<rand.0.34006561>,type => exsss,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               uniform => #Fun<rand.1.34006561>,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               uniform_n => #Fun<rand.2.34006561>},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             [2150540948049099|39771336696590305]}},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {{prot_vsn,'rabbit@r1-server-4.r1-nodes.default'},8},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {{sync_tag_his,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             'rabbit@r1-server-3.r1-nodes.default'},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            -576460752303423477},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {creation_extension,20109732664573952},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {'$initial_call',{global,init,1}},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {'$ancestors',[kernel_sup,<0.47.0>]},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {{sync_tag_his,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             'rabbit@r1-server-4.r1-nodes.default'},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            -576460752303423469},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {{pre_connect,'rabbit@r1-server-4.r1-nodes.default'},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            {8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             {locker,no_longer_a_pid,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                              #{'rabbit@r1-server-0.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                'rabbit@r1-server-1.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                'rabbit@r1-server-3.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-0.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 6631665,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-1.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 9346854,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-2.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 9344269,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-3.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 6616455},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                              <25934.56.0>},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             -576460752303423469}}],
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                          running,<0.49.0>,[],
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                          [{header,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            "Status for generic server global_name_server"},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {data,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            [{"Status",running},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             {"Parent",<0.49.0>},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                             {"Logged events",[]}]},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                           {data,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                            [{"State",
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                              {state,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               {conf,true,false},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               #{'rabbit@r1-server-0.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-1.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-3.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 'rabbit@r1-server-4.r1-nodes.default' => 8,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  'rabbit@r1-server-0.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  12032275,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  'rabbit@r1-server-1.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  1029715,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  'rabbit@r1-server-3.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  1027052,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                 {connection_id,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  'rabbit@r1-server-4.r1-nodes.default'} =>
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                  1021319},
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               ['rabbit@r1-server-0.r1-nodes.default',
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                                'rabbit@r1-server-1.r1-nodes.default'],
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               [],
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               [<0.426.0>],
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               'rabbit@r1-server-2.r1-nodes.default',<0.56.0>,
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0>                               <0.57.0>,no_trace,false}}]}]]}
2022-10-06 07:13:25.070793+00:00 [debug] <0.425.0> Faking nodedown/nodeup between rabbit@r1-server-3.r1-nodes.default and rabbit@r1-server-2.r1-nodes.default
2022-10-06 07:13:25.073375+00:00 [warning] <0.55.0> The global_name_server received an unexpected message:
2022-10-06 07:13:25.073375+00:00 [warning] <0.55.0> handle_info({nodedown,'rabbit@r1-server-3.r1-nodes.default'}, _)
2022-10-06 07:13:25.073375+00:00 [warning] <0.55.0>
2022-10-06 07:13:25.073521+00:00 [warning] <0.55.0> The global_name_server received an unexpected message:
2022-10-06 07:13:25.073521+00:00 [warning] <0.55.0> handle_info({nodeup,'rabbit@r1-server-3.r1-nodes.default'}, _)
2022-10-06 07:13:25.073521+00:00 [warning] <0.55.0>
</details>

### PR DESCRIPTION
**Pull request by ansd**
Fixes #6034 

I manually validated on `kind` and K8s version `1.25.2` that the "global hang workaround" in this PR works for:
* Erlang 25.1.1 cluster formation + rolling update
* Erlang 25.0.4 cluster formation + rolling update
* rolling update from RabbitMQ 3.8.10 on Erlang 23.2.3 to this branch using Erlang 25.1.1

(We have additionally pipelines testing rolling updates.)

We need to backport this PR up to 3.10.x because 3.10.x supports OTP 25.1 (while 3.9.x supports maximum OTP 24.3).

### CODE REVIEW

File: deps/rabbit/src/rabbit_node_monitor.erl [hunk 1]
```diff
@@ -323,20 +326,53 @@ find_blocked_global_peers1([], _) ->
 
 unblock_global_peer(PeerNode) ->
     ThisNode = node(),
-    PeerState = rpc:call(PeerNode, sys, get_status, [global_name_server]),
+
+    {status, _, _, [_, _, _, _, PeerState]} = PeerStatus =
+        erpc:call(PeerNode, sys, get_status, [global_name_server]),
+    {status, _, _, [_, _, _, _, ThisState]} = ThisStatus =
+        sys:get_status(global_name_server),
```
Comment (dumbbell) [inline deps/rabbit/src/rabbit_node_monitor.erl:333]: You should use `sys:get_state/1` now to get the state directly, without having to parse the return value of `sys:get_status/1`.

File: deps/rabbit/src/rabbit_node_monitor.erl [hunk 2]
```diff
@@ -323,20 +326,53 @@ find_blocked_global_peers1([], _) ->
...
+    {ThisDownMsg, ThisUpMsg} = messages(ThisToPeerCid, PeerNode),
+    {PeerDownMsg, PeerUpMsg} = messages(PeerToThisCid, ThisNode),
+    {global_name_server, ThisNode} ! ThisDownMsg,
+    {global_name_server, PeerNode} ! PeerDownMsg,
+    {global_name_server, ThisNode} ! ThisUpMsg,
+    {global_name_server, PeerNode} ! PeerUpMsg,
     ok.
 
+connection_id(Misc, Node) ->
+    [State] = [S || {data, [{"State", S}]} <- Misc],
```
Comment (dumbbell) [inline deps/rabbit/src/rabbit_node_monitor.erl:355]: After using `sys:get_state/1`, you can skip this, you'll have `State` directly.

File: deps/rabbit/src/rabbit_node_monitor.erl [hunk 3]
```diff
@@ -323,20 +326,53 @@ find_blocked_global_peers1([], _) ->
...
+    state = element(1, State),
```
Comment (dumbbell) [inline deps/rabbit/src/rabbit_node_monitor.erl:356]: Could you please use `?assertEqual(state, element(1, State)),` instead? It will raise an exception which will make it clear we hit an assertion.

You will have to `-include_lib("stdlib/include/assert.hrl").`, not the EUnit header.

**Review by dumbbell — CHANGES_REQUESTED** [review]
I like the patch, that's a good find!

My comments are just about some code simplification.

File: deps/rabbit/src/rabbit_node_monitor.erl (hunk 1 above)
Comment (ansd) [reply deps/rabbit/src/rabbit_node_monitor.erl:333]: I first used `sys:get_state/1`, but moved to `sys:get_status/1` because the docs for `sys:get_state/1` say:
>These functions are intended only to help with debugging. They are provided for convenience, allowing developers to avoid having to create their own state extraction functions and also avoid having to interactively extract the state from the return values of get_status/1 or get_status/2 **while debugging**.

But I can move back to  `sys:get_state/1` if you think it's safe to use in production?

File: deps/rabbit/src/rabbit_node_monitor.erl [hunk 4]
```diff
@@ -323,20 +326,53 @@ find_blocked_global_peers1([], _) ->
...
+    case element(3, State) of
+        Known when is_map(Known) ->
+            maps:get({connection_id, Node}, Known, undefined);
```
[the remark this answers is not in the document]
Comment (ansd) [reply deps/rabbit/src/rabbit_node_monitor.erl:359]: Yes, that's better, thank you.

File: deps/rabbit/src/rabbit_node_monitor.erl (hunk 1 above)
Comment (ansd) [reply deps/rabbit/src/rabbit_node_monitor.erl]: I changed it back to `sys:get_state/1`.

File: deps/rabbit/src/rabbit_node_monitor.erl (hunk 2 above)
Comment (ansd) [reply deps/rabbit/src/rabbit_node_monitor.erl]: Done, thank you.

File: deps/rabbit/src/rabbit_node_monitor.erl (hunk 3 above)
Comment (ansd) [reply deps/rabbit/src/rabbit_node_monitor.erl]: Thanks, that's a good tip. Given that I changed back to `sys:get_state/1`, I completely removed that assertion. (The assertion was mainly meant to check that we parse the state correctly from `sys:get_status/1`.)

**Comment by ansd** [comment]
Thank you for reviewing @dumbbell.
I validated again with the latest changes that the workaround works as expected with `pivotalrabbitmq/rabbitmq:global-hang-workaround-otp-max-bazel` and `pivotalrabbitmq/rabbitmq:global-hang-workaround-otp-min-bazel`.

**Review by dumbbell — APPROVED** [review]
