### PR TITLE
CLI: set OTP logger log level to 'error'

### LINKED ISSUE #8912: CLI: some warnings are sent to standard output
### Describe the bug

The `rabbitmqctl` tool that comes with RabbitMQ 3.11.20 sends its warnings to the standard output stream instead of the standard error stream. This causes problems with scripts that use it with e.g. `--formatter json`

### Reproduction steps

1. Have some settings that cause a warning to be issued when using `rabbitmqctl` (e.g. disable TLS server authenticity checks).
2. Run e.g. `rabbitmqctl cluster_status --formatter json 2>/dev/null`

### Expected behavior

The command above should only display the JSON-formatted data. Instead, the output starts with warnings and then contains the JSON data.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by michaelklishin**
Closes #8912

### CODE REVIEW

File: deps/rabbitmq_cli/lib/rabbitmqctl.ex [hunk 1]
```diff
@@ -26,10 +26,18 @@ defmodule RabbitMQCtl do
 
   @spec main(list()) :: no_return()
   def main(["--auto-complete" | []]) do
+    # silence Erlang/OTP's standard library warnings, it's acceptable for CLI tools,
+    # see rabbitmq/rabbitmq-server#8912
+    :logger.set_primary_config(:level, :error)
```
Comment (the-mikedavis) [inline deps/rabbitmq_cli/lib/rabbitmqctl.ex:31]:
```suggestion
    _ = :logger.set_primary_config(:level, :error)
```

File: deps/rabbitmq_cli/lib/rabbitmqctl.ex [hunk 2]
```diff
@@ -26,10 +26,18 @@ defmodule RabbitMQCtl do
...
+
     handle_shutdown(:ok)
   end
 
   def main(unparsed_command) do
+    # silence Erlang/OTP's standard library warnings, it's acceptable for CLI tools,
+    # see rabbitmq/rabbitmq-server#8912
+    :logger.set_primary_config(:level, :error)
```
Comment (the-mikedavis) [inline deps/rabbitmq_cli/lib/rabbitmqctl.ex:39]:
```suggestion
    _ = :logger.set_primary_config(:level, :error)
```

**Review by the-mikedavis — COMMENTED** [review]
Looks like the dialyzer warns about these unmatched return values. Otherwise I think this looks good 👍
