### PR TITLE
Do not crash on badarg when env file has certain Unicode characters

### LINKED ISSUE #3212: Unicode character in HOSTNAME prevents RabbitMQ from starting
When the HOSTNAME contains a Unicode character, for example https://www.fileformat.info/info/unicode/char/2019/index.htm, the node cannot start due to the following crash:

```
12:59:24.165 [error]     supervisor:do_start_child_i/3 line 414
12:59:24.165 [error]     rabbit_prelaunch:run_prelaunch_first_phase/0 line 27
12:59:24.165 [error]     rabbit_prelaunch:do_run/0 line 87
12:59:24.165 [error]     lists:foldl/3 line 1267
12:59:24.165 [error]     rabbit_env:parse_conf_env_file_output1/2 line 1612
12:59:24.165 [error]     rabbit_env:parse_conf_env_file_output2/2 line 1633
12:59:24.165 [error]     rabbit_env:is_sh_set_x_output/1 line 1656
12:59:24.165 [error]     re:run([...,8217,...], "^\\++ ", [{capture,none}])
12:59:24.166 [error] error:badarg
```

It happens at least on OTP 24 and 3.8.19.

There are still some unknowns (like in which file this happens) but I think this can be acted upon. The solution is probably to convert the string to a Unicode binary before calling `re:run`.

The discussion context can be found in https://rabbitmq.slack.com/archives/C1EDN83PA/p1626458869383300

### PR DESCRIPTION
**Pull request by deadtrickster**
closes #3212

## Proposed Changes

As proposed by @lhoguin, converting using `unicode:characters_to_binary` helps.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

File: deps/rabbit_common/src/rabbit_env.erl [hunk 1]
```diff
@@ -1718,14 +1718,14 @@ parse_conf_env_file_output2([Line | Lines], Vars) ->
     end.
 
 is_sh_set_x_output(Line) ->
-    re:run(Line, "^\\++ ", [{capture, none}]) =:= match.
+    re:run(unicode:characters_to_binary(Line), "^\\++ ", [{capture, none}]) =:= match.
```
Comment (dumbbell) [inline deps/rabbit_common/src/rabbit_env.erl:1721]: Could you please split the line to make it fit in 80 columns?

Like:
```erlang
    UnicodeLine = unicode:characters_to_binary(Line),
    re:run(UnicodeLine, "^\\++ ", [{capture, none}]) =:= match.
```

File: deps/rabbit_common/src/rabbit_env.erl [hunk 2]
```diff
@@ -1718,14 +1718,14 @@ parse_conf_env_file_output2([Line | Lines], Vars) ->
...
 
 is_sh_function(_, []) ->
     false;
 is_sh_function(Line, Lines) ->
-    re:run(Line, "\\s\\(\\)\\s*$", [{capture, none}]) =:= match
+    re:run(unicode:characters_to_binary(Line), "\\s\\(\\)\\s*$", [{capture, none}]) =:= match
     andalso
-    re:run(hd(Lines), "^\\s*\\{\\s*$", [{capture, none}]) =:= match.
+    re:run(unicode:characters_to_binary(hd(Lines)), "^\\s*\\{\\s*$", [{capture, none}]) =:= match.
```
Comment (dumbbell) [inline deps/rabbit_common/src/rabbit_env.erl:1728]: Likewise for this chunk. For example:
```erlang
    UnicodeLine1 = unicode:characters_to_binary(Line),
    UnicodeLine2 = unicode:characters_to_binary(hd(Lines)),
    re:run(UnicodeLine1, "\\s\\(\\)\\s*$", [{capture, none}]) =:= match
    andalso
    re:run(UnicodeLine2, "^\\s*\\{\\s*$", [{capture, none}]) =:= match.
```

**Review by dumbbell — CHANGES_REQUESTED** [review]

File: deps/rabbit_common/test/rabbit_env_SUITE.erl [hunk 3]
```diff
@@ -1080,7 +1080,8 @@ check_parse_conf_env_file_output(_) ->
          "DOUBLE_QUOTED" => "c",
          "SINGLE_DOLLAR" => "d"},
        rabbit_env:parse_conf_env_file_output2(
-         ["UNQUOTED=a",
+         ["++ ؎ ", %% note unicode char
```
Comment (lhoguin) [inline deps/rabbit_common/test/rabbit_env_SUITE.erl:1083]: You should have a test that produces a value you can assert against as well.

**Review by lhoguin — CHANGES_REQUESTED** [review]

File: deps/rabbit_common/src/rabbit_env.erl (hunk 2 above)
Comment (deadtrickster) [reply deps/rabbit_common/src/rabbit_env.erl]: Ended up using this approach. Not perfect because we compute UnicodeLine2 outside of short-circuit, but the rest of the rabbit_env with functions like parse_unquoted_literal and rabbit_env_SUITE expects erlang strings. Too big rewrite to do.

File: deps/rabbit_common/test/rabbit_env_SUITE.erl (hunk 3 above)
Comment (deadtrickster) [reply deps/rabbit_common/test/rabbit_env_SUITE.erl:1084]: Well I added the test, but because it's erlang string - kinda ugly (the array).

Comment (michaelklishin) [reply deps/rabbit_common/test/rabbit_env_SUITE.erl:1084]: This is a [Unicode character](https://unicode-table.com/en/060E/). The whole issue is likely about non-ASCII characters.

We can use something a bit more readable than that, too: a short Mandarin, Cyrillic or Hindi word.

**Review by michaelklishin — CHANGES_REQUESTED** [review]

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Backported to `v3.9.x`.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.
