### PR TITLE
Remove Powershell as a backup to `handle.exe`

### LINKED ISSUE #8700: Using Powershell as a backup for handle.exe is not a good solution.
### Describe the bug

We have had a couple Windows users report excessive CPU use of Powershell when it is used to calculate the number of handles being used by RabbitMQ. This was introduced by #6614 as a fix to #6613. 

* https://stackoverflow.com/questions/76575596/rabbitmq-continually-spawns-powershell-which-results-in-100-cpu-usage
* https://groups.google.com/g/rabbitmq-users/c/hYOCHG1aCss
* https://github.com/rabbitmq/rabbitmq-server/discussions/8541

We know that `handle.exe` sometimes does not return valid information, and of course sometimes is not installed. On Windows, keeping track of used handles (file descriptors) is not as critical as on Linux. Perhaps the best solution is to remove the Powershell backup.

### Reproduction steps

Run RabbitMQ on Windows without installing `handle.exe`.

### Expected behavior

No high CPU usage no matter how we calculate handle usage.

### Additional context

N/A

### PR DESCRIPTION
**Pull request by lukebakken**
If a user does not have `handle.exe` installed in the `PATH` of their Windows system, a message will be logged once, and then the total handles being used will be set to `0`.

Fixes #8700

Follow-up to:
* #6614
* #6613
* #8541

### CODE REVIEW

File: deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl [hunk 1]
```diff
@@ -108,25 +108,23 @@ get_used_fd({win32, _}, State0) ->
     case os:find_executable("handle.exe") of
         false ->
             State1 = log_fd_warning_once("Could not find handle.exe, using powershell to determine handle count", [], State0),
```
Comment (mkuratczyk) [inline deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl:110]: This log message is no longer correct, is it?

Comment (lukebakken) [reply deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl:110]: Yessir, I sure missed that one.

**Review by mkuratczyk — APPROVED** [review]
