### PR TITLE
tcp_listener: avoid logging listener arguments on shutdown

### LINKED ISSUE #3803: Failed listener startup can log private key password in crash.log
When rabbitmq crashed In some scenarios, the crash.log logged the  the sensitive value such as the password of certificate private key, which will cause possible information leak.
Perhaps we should mask the  password before print it in logs。 

The crash.log is below:

```
2021-11-22 21:22:26 =SUPERVISOR REPORT====
     Supervisor: {<0.2000.0>,tcp_listener_sup}
     Context:    shutdown_error
     Reason:     {aborted,{node_not_running,'rabbit@rabbitmqservice-0'}}
     Offender:   [{pid,<0.2019.0>},{id,tcp_listener},{mfargs,{tcp_listener,start_link,[{xxx,xx,x,xxx},5673,{rabbit_networking,tcp_listener_started,['amqp/ssl',[{backlog,128},{nodelay,true},{linger,{true,0}},{exit_on_close,false},{versions,['tlsv1.2']},{cacertfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/xxx_CA.pem"},{certfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/xxx_cer.pem"},{keyfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/PrivateKey.pem"},**{password,"abcdefghabcdefghabcdefghabcdefgh"},**{verify,verify_peer},{fail_if_no_peer_cert,false},{honor_cipher_order,true},{honor_ecc_order,true},{ciphers,["ECDHE-RSA-AES256-GCM-SHA384","DHE-RSA-AES256-GCM-SHA384","ECDHE-RSA-AES128-GCM-SHA256","DHE-RSA-AES128-GCM-SHA256"]}]]},{rabbit_networking,tcp_listener_stopped,['amqp/ssl',[{backlog,128},{nodelay,true},{linger,{true,0}},{exit_on_close,false},{versions,['tlsv1.2']},{cacertfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/xxx_CA.pem"},{certfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/xxx_cer.pem"},{keyfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/PrivateKey.pem"},**{password,"abcdefghabcdefghabcdefghabcdefgh"},**{verify,verify_peer},{fail_if_no_peer_cert,false},{honor_cipher_order,true},{honor_ecc_order,true},{ciphers,["ECDHE-RSA-AES256-GCM-SHA384","DHE-RSA-AES256-GCM-SHA384","ECDHE-RSA-AES128-GCM-SHA256","DHE-RSA-AES128-GCM-SHA256"]}]]},"TLS (SSL) listener"]}},{restart_type,transient},{shutdown,4294967295},{child_type,worker}]

2021-11-22 21:22:26 =ERROR REPORT====
** Generic server <0.2019.0> terminating 
** Last message in was {'EXIT',<0.2000.0>,shutdown}
** When Server state == {state,{rabbit_networking,tcp_listener_started,['amqp/ssl',[{backlog,128},{nodelay,true},{linger,{true,0}},{exit_on_close,false},{versions,['tlsv1.2']},{cacertfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/xxx_CA.pem"},{certfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/xxx_cer.pem"},{keyfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/PrivateKey.pem"},**{password,"abcdefghabcdefghabcdefghabcdefgh"},**{verify,verify_peer},{fail_if_no_peer_cert,false},{honor_cipher_order,true},{honor_ecc_order,true},{ciphers,["ECDHE-RSA-AES256-GCM-SHA384","DHE-RSA-AES256-GCM-SHA384","ECDHE-RSA-AES128-GCM-SHA256","DHE-RSA-AES128-GCM-SHA256"]}]]},{rabbit_networking,tcp_listener_stopped,['amqp/ssl',[{backlog,128},{nodelay,true},{linger,{true,0}},{exit_on_close,false},{versions,['tlsv1.2']},{cacertfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/xxx_CA.pem"},{certfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/xxx_cer.pem"},{keyfile,"/usr/local/rabbitmq_server-3.8.22/secret_file/PrivateKey.pem"},**{password,"abcdefghabcdefghabcdefghabcdefgh"},**{verify,verify_peer},{fail_if_no_peer_cert,false},{honor_cipher_order,true},{honor_ecc_order,true},{ciphers,["ECDHE-RSA-AES256-GCM-SHA384","DHE-RSA-AES256-GCM-SHA384","ECDHE-RSA-AES128-GCM-SHA256","DHE-RSA-AES128-GCM-SHA256"]}]]},"TLS (SSL) listener",{xxx,xx,x,xxx},5673}
** Reason for termination ==
** {{aborted,{node_not_running,'rabbit@rabbitmqservice-0'}},[{mnesia,abort,1,[{file,"mnesia.erl"},{line,361}]},{mnesia_tm,prepare_items,5,[{file,"mnesia_tm.erl"},{line,1225}]},{mnesia_tm,dirty,2,[{file,"mnesia_tm.erl"},{line,1067}]},{rabbit_networking,tcp_listener_stopped,4,[{file,"src/rabbit_networking.erl"},{line,350}]},{gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,727}]},{gen_server,terminate,10,[{file,"gen_server.erl"},{line,912}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2021-11-22 21:22:26 =CRASH REPORT====
  crasher:
    initial call: tcp_listener:init/1
    pid: <0.2019.0>
    registered_name: []
    exception exit: {{aborted,{node_not_running,'rabbit@rabbitmqservice-0'}},[{mnesia,abort,1,[{file,"mnesia.erl"},{line,361}]},{mnesia_tm,prepare_items,5,[{file,"mnesia_tm.erl"},{line,1225}]},{mnesia_tm,dirty,2,[{file,"mnesia_tm.erl"},{line,1067}]},{rabbit_networking,tcp_listener_stopped,4,[{file,"src/rabbit_networking.erl"},{line,350}]},{gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,727}]},{gen_server,terminate,10,[{file,"gen_server.erl"},{line,912}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.2000.0>,rabbit_sup,<0.1282.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 28
    reductions: 2992
  neighbours:
```

### PR DESCRIPTION
**Pull request by michaelklishin**
Even if exception occurs.

While at it, encrypt memory-stored arguments that might contain sensitive values.

Closes #3803.

### CODE REVIEW

File: deps/rabbit/src/tcp_listener.erl [hunk 1]
```diff
@@ -79,9 +87,37 @@ handle_cast(_Msg, State) ->
...
+                     [Label, rabbit_misc:ntoab(IPAddress), Port, Error])
+    end.
 
 code_change(_OldVsn, State, _Extra) ->
     {ok, State}.
+
+obfuscate_state(#state{on_startup = OnStartup, on_shutdown = OnShutdown} = State) ->
+    State#state{
+        on_startup  = credentials_obfuscation:encrypt(term_to_binary(OnStartup)),
+        on_shutdown = credentials_obfuscation:encrypt(term_to_binary(OnShutdown))
```
Comment (lhoguin) [inline deps/rabbit/src/tcp_listener.erl:106]: Instead of doing encrypt and TTB you can just do `fun(IPAddress, Port) -> apply(M, F, A ++ [IPAddress, Port]) end` as the MFAs will be captured and hidden inside the fun.

File: deps/rabbit/src/tcp_listener.erl [hunk 2]
```diff
@@ -63,12 +63,20 @@ start_link(IPAddress, Port,
...
+init({IPAddress, Port, {M, F, A} = OnStartup, OnShutdown, Label}) ->
+    ensure_credential_obfuscation_secret(),
+
     process_flag(trap_exit, true),
     logger:info("started ~s on ~s:~p", [Label, rabbit_misc:ntoab(IPAddress), Port]),
     apply(M, F, A ++ [IPAddress, Port]),
-    {ok, #state{on_startup = OnStartup, on_shutdown = OnShutdown,
-                label = Label, ip=IPAddress, port=Port}}.
+    State0 = #state{
+        on_startup = OnStartup,
```
Comment (lhoguin) [inline deps/rabbit/src/tcp_listener.erl:73]: Do we even need to store `on_startup`? It's not used. I would just remove it from the record.

File: deps/rabbit/src/tcp_listener.erl (hunk 1 above)
Comment (lhoguin) [reply deps/rabbit/src/tcp_listener.erl:106]: This would be done in the init function, and the apply in terminate can be replaced with `OnShutdownFun(IPAddress, Port)`.

**Comment by polaris-alioth** [comment]
With OnStartup and  OnShutdown encrypted, will the encryped tcp listener arguments be logged instead?

**Comment by lhoguin** [comment]
When encrypted the encrypted data will be stored yes. With a fun it would store something like `#Fun<tcp_listener.0.29874839>`.

**Review by lhoguin — APPROVED** [review]
