### PR TITLE
fixes various dialyzer warnings

### LINKED ISSUE #441: fix various dialyzer warnings

### PR DESCRIPTION
**Pull request by videlalvaro**
Fixes #441

### CODE REVIEW

File: src/pg2_fixed.erl [hunk 1]
```diff
@@ -265,12 +266,10 @@ terminate(_Reason, _S) ->
...
 
 store(List) ->
-    _ = [case assure_group(Name) of
-             true ->
-                 [join_group(Name, P) || P <- Members -- group_members(Name)];
-             _ ->
-                 ok
-         end || [Name, Members] <- List],
+    _ = [assure_group(Name)
+         andalso
```
Comment (videlalvaro) [inline src/pg2_fixed.erl]: See https://github.com/erlang/otp/blob/1523be48ab4071b158412f4b06fe9c8d6ba3e73c/lib/kernel/src/pg2.erl#L263
